setwd("~Desktop/Data_Science_Specialist")
install.packages("AppliedPredictiveModeling")
install.packages("lattice")
install.packages("lubridate")
install.packages("ggplot2")
install.packages("CORElearn")
install.packages("caret")
data <- read.csv("activity.csv", header = TRUE, sep = ",", na.strings = "NA")
summary(data)
str(data)
head(data)
data$date <- as.Date(data$date, format = "%Y-%m-%d")
data$interval <- factor(data$interval)
NA_index <- is.na(as.character(data$steps))
data_no_NA <- data[!NA_index,]
head(data_no_NA)